version: '3.8'
services:
  client:
    container_name: client
    build:
      dockerfile: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    links:
      - server
  server:
    container_name: server
    build:
      dockerfile: ./server
    ports:
      - '5000:5000'

