name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Docker Compose
    #   run: |
    #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #     sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: SSH into EC2 instance and deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: your-ec2-instance-ip
    #     username: your-ec2-instance-username
    #     key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /path/to/your/app
    #       docker-compose pull
    #       docker-compose up -d